AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: MDM to RDM Data Migration Components
Parameters:
  pGlueServiceRoleName:
    Type: String
    Description: Glue Service Role Name  
  pGlueJobName:
    Description: Glue Job Name
    Type: String
  pGlueTriggerName:
    Description: Glue Trigger Name
    Type: String   
  pGlueJobScriptlocation:
    Description: Glue Job Script Location
    Type: String 
  pGlueJobPythonLibPath:
    Description: Glue Job Python Lib Location
    Type: String    
  pParamsBucket:
    Description: Params Bucket
    Type: String    
  pParamsKey:
    Description: Params Key
    Type: String 
  pRDMConfigBucket:
    Description: RDM Config Output Bucket
    Type: String    
  pRDMConfigKey:
    Description: RDM Config Output Key
    Type: String
  pRDMFilesBucket:
    Description: RDM Files Output Bucket
    Type: String    
  pRDMFilesKey:
    Description: RDM Files Output Key
    Type: String
  pGlueJobMaxConcurrency:
    Description: Glue Job Max Concurrancy
    Type: String
  pGlueJobWorkers:
    Description: Glue Job Number of Workers
    Type: String


Globals:
  Function:
    Timeout: 3    

Resources: 
  rGlueJob:
      Type: AWS::Glue::Job
      Properties:
        Name: !Ref pGlueJobName
        Role: !Ref pGlueServiceRoleName
        Description: "Glue job for MDM to RDM Data Migration"
        Command:
          Name: glueetl
          PythonVersion: "3"
          ScriptLocation: !Ref pGlueJobScriptlocation  
        GlueVersion: "3.0"
        WorkerType : "G.1X"
        NumberOfWorkers: !Ref pGlueJobWorkers    
        DefaultArguments: { "--paramsfilebucket": "",
                            "--paramsfilekey": "",
                            "--rdmconfigbucket": "",
                            "--rdmconfigkey": "",
                            "--rdmfilesbucket": "",
                            "--rdmfileskey": "",
                            "--secretid": "",
                            "--extra-py-files": !Sub "${pGlueJobPythonLibPath}",
                            "--enable-metrics": ""
                          }
        ExecutionProperty:
          MaxConcurrentRuns: !Ref pGlueJobMaxConcurrency